### PR TITLE
Move inputs to ignored if mk_output fails for build_tx_and_clear

### LINKED ISSUE #40: Missing adding to ignored
https://github.com/input-output-hk/chain-wallet-libs/blob/aa0a690dc5f542b0b51a155c5561fe6272369481/wallet/src/transaction/dump.rs#L71-L87

In this, if the mk_output fails, the inputs need to move to ignored.

### PR DESCRIPTION
**Pull request by danielSanchezQ**
Fixes #40

### CODE REVIEW

File: wallet/src/transaction/dump.rs [hunk 1]
```diff
@@ -84,6 +84,8 @@ impl Dump {
             let builder = builder.set_witnesses(&witnesses);
             let tx = builder.set_payload_auth(&());
             self.outputs.push(tx);
+        } else {
+            self.ignored.extend_from_slice(self.inputs.as_slice());
```
Comment (NicolasDP) [inline wallet/src/transaction/dump.rs:88]: don't you need to take ownership of the inputs here?

Comment (danielSanchezQ) [reply wallet/src/transaction/dump.rs:88]: They are cloned there internally. It should be ok since we clear the inputs vector later.
